name: Ejecutar bot diariamente

on:
  schedule:
    - cron: "0 12 * * *"  # Ejecuta todos los días a las 7 AM hora Miami (UTC-5)
  workflow_dispatch:  # permite ejecutarlo manualmente desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar script
        run: python main.py
